ALTER TABLE MAPAS ADD COLUMN center GEOMETRY(Point, 4326) NOT NULL,
    ADD COLUMN bbox GEOMETRY(Polygon, 4326) NOT NULL,
    ADD COLUMN zoom_inicial NUMERIC(4,1) NOT NULL DEFAULT 12.0,
    ADD COLUMN zoom_min NUMERIC(4,1) NOT NULL DEFAULT 9.0,
    ADD COLUMN zoom_max NUMERIC(4,1) NOT NULL DEFAULT 18.0;